{application,decimal,
             [{config_mtime,1726399662},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir]},
              {description,"Arbitrary precision decimal arithmetic."},
              {modules,['Elixir.Decimal','Elixir.Decimal.Context',
                        'Elixir.Decimal.Error','Elixir.Decimal.Macros',
                        'Elixir.Inspect.Decimal',
                        'Elixir.String.Chars.Decimal']},
              {registered,[]},
              {vsn,"2.1.1"}]}.
